apiVersion: apps/v1
kind: Deployment
metadata:
  name: brutal
  namespace: default
  labels:
    app: brutal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brutal
  template:
    metadata:
      labels:
        app: brutal
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
        - name: brutal
          image: us-ashburn-1.ocir.io/iduqwkepwfyc/brutal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000