apiVersion: v1
kind: Service
metadata:
  name: brutal-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: brutal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000